using System;
using System.Collections.Generic;

namespace Phoenix.Data.Plc.AgLink
{
	internal class AgLinkErrorMapping
	{
		public static Dictionary<string, string> ErrorCodeMapping { get; set; }

		static AgLinkErrorMapping()
		{
			ErrorCodeMapping = new Dictionary<string, string>()
			{
				{ "00000000" , "No error" },
				{ "00000001" , "No error, job still in process" },
				{ "FFF00000" , "Function not implemented" },
				{ "FFF00001" , "Parameter error when calling function" },
				{ "FFF00002" , "Invalid device number" },
				{ "FFF00003" , "Invalid PLC number" },
				{ "FFF00004" , "Invalid parameter type" },
				{ "FFF00005" , "Insufficient memory" },
				{ "FFF00006" , "Device already opened" },
				{ "FFF00007" , "Device not opened" },
				{ "FFF00008" , "Job removed" },
				{ "FFF00009" , "Invalid job number" },
				{ "FFF0000A" , "Function not supported" },
				{ "FFF0000B" , "Adapter not initialized" },
				{ "FFF0000C" , "No free connections available" },
				{ "FFF0000D" , "Device not configured or not supported" },
				{ "FFF0000E" , "Hardware not found" },
				{ "FFF0000F" , "Error when reading parameters" },
				{ "FFF00010" , "Error when writing parameters" },
				{ "FFF00011" , "Demo period expired" },
				{ "FFF00012" , "Wrong character in text. Conversion not possible" },
				{ "FFF00013" , "Buffer is not long enough" },
				{ "FFF00014" , "File not found" },
				{ "FFF00015" , "Error when calling configuration program" },
				{ "FFF00016" , "Error when loading DLL dynamically" },
				{ "FFF00017" , "Could not create file" },
				{ "FFF00018" , "Notification type already in use" },
				{ "FFF00019" , "Running job already removed" },
				{ "FFF0001A" , "Job already removed" },
				{ "FFF0001B" , "Error when reading WLD file" },
				{ "FFF0001C" , "Error when writing WLD file" },
				{ "FFF0001D" , "Invalid structure in WLD file" },
				{ "FFF0001E" , "Multiple blocks in WLD file" },
				{ "FFF0001F" , "Function is not reentrant" },
				{ "FFF00020" , "Function removed for code size reduction" },
				{ "FFF50000" , "No free job buffer available" },
				{ "FFF50001" , "Invalid packet" },
				{ "FFF50002" , "No connection to PLC" },
				{ "FFF50003" , "Connection closed" },
				{ "FFF50004" , "Timeout" },
				{ "FFF50005" , "Invalid context" },
				{ "FFF50006" , "PLC memory error" },
				{ "FFF50007" , "Invalid operating state" },
				{ "FFF50008" , "Invalid address on PLC" },
				{ "FFF50009" , "Invalid mode" },
				{ "FFF5000A" , "No data available e.g. DB is missing" },
				{ "FFF5000B" , "Priority class associated to OB does not exist" },
				{ "FFF5000C" , "Empty blocklist" },
				{ "FFF5000D" , "Block size error" },
				{ "FFF5000E" , "Invalid block number" },
				{ "FFF5000F" , "Protection level of function not sufficient" },
				{ "FFF50010" , "Unknown SSL-ID (e.g. access to CP instead of PLC)" },
				{ "FFF50011" , "Unknown SSL-index (e.g. access to CP instead of PLC)" },
				{ "FFF50012" , "Information currently not ascertainable" },
				{ "FFF50013" , "Unknown error message from PLC (please report!)" },
				{ "FFF50014" , "Hardware error e.g. not available periphery" },
				{ "FFF50015" , "Object access not allowed" },
				{ "FFF50016" , "Context not supported" },
				{ "FFF50017" , "Type (data type) not supported" },
				{ "FFF50018" , "Internal error, please report" },
				{ "FFF50019" , "Error rebooting PLC" },
				{ "FFF5001A" , "Error restarting PLC" },
				{ "FFF5001B" , "Connection end received" },
				{ "FFF5001C" , "PLC not found" },
				{ "FFF5001D" , "Too many data for this version of ACCON-AGLink" },
				{ "FFF5001E" , "PLC does not support this function" },
				{ "FFF5001F" , "Wrong Password" },
				{ "FFF50020" , "Connection already legitimated" },
				{ "FFF50021" , "Legitimation already released" },
				{ "FFF50022" , "Password not neccessary" },
				{ "FFF50023" , "At least one variable address invalid" },
				{ "FFF50024" , "Job does not exist" },
				{ "FFF50025" , "Invalid job state" },
				{ "FFF50026" , "Invalid cycle time" },
				{ "FFF50027" , "No more cyclic job possible" },
				{ "FFF50028" , "Function not posible for this job (invalid state)" },
				{ "FFF50029" , "Function abort (overload)" },
				{ "FFF5002A" , "No data for this variable" },
				{ "FFF5002B" , "Wrong time format" },
				{ "FFF5002C" , "Unknown PI name" },
				{ "FFF5002D" , "File transfer canceled by NCK" },
				{ "FFF5002E" , "Response too large for PDU size" },
				{ "FFF5002F" , "No H-PLC found" },
				{ "FFF50030" , "Data not changed" },
				{ "FFF50031" , "Received data is corrupt" },
				{ "FFF50032" , "The requested parameter has the wrong size or type" },
				{ "FFF50033" , "The parameter has a wrong value" },
				{ "FFF50034" , "The parameter is not changeable" },
				{ "FFF50035" , "The parameter is read only" },
				{ "FFF50036" , "The variable definition contains the wrong size" },
				{ "FFF50037" , "Array index does not exist" },
				{ "FFF50038" , "PARA does not exist" },
				{ "FFF30000" , "Error when reading device information" },
				{ "FFF30001" , "Error when reading bus parameters" },
				{ "FFF30002" , "Error when writing bus parameters" },
				{ "FFF30003" , "No resources available on device" },
				{ "FFF30004" , "Invalid device" },
				{ "FFF30005" , "Adapter not found" },
				{ "FFF30006" , "Needed device driver not found" },
				{ "FFF20000" , "The desired adapter address already exists" },
				{ "FFF20001" , "Invalid HSA (smaller than biggest active participant)" },
				{ "FFF20002" , "Adapter is not in the logical ring" },
				{ "FFF20004" , "Received package has wrong content" },
				{ "FFF20006" , "Unknown error number from adapter" },
				{ "FFF20007" , "Unknown error number from device driver" },
				{ "FFF20008" , "Communications adapter has been removed" },
				{ "FFF20009" , "Modem has been removed" },
				{ "FFF2000A" , "No directly connected PLC found" },
				{ "FFF20313" , "Invalid speed on MPI bus" },
				{ "FFF20314" , "Address is bigger than HSA" },
				{ "FFF20315" , "The desired adapter address already exists" },
				{ "FFF2031A" , "No other active bus participants found" },
				{ "FFF2031C" , "Bus is jammed" },
				{ "FFF2031D" , "Bus is jammed" },
				{ "FFF2031E" , "Automatic detection of bus profile doesn't work, missing bus parameter telegram" },
				{ "FFF20337" , "Legitimation missing" },
				{ "FFF10000" , "COM-Port already used" },
				{ "FFF10001" , "Modem not found" },
				{ "FFF10002" , "Modem not onhook" },
				{ "FFF10003" , "Modem not offhook" },
				{ "FFF10004" , "Error in basic initialisation" },
				{ "FFF10005" , "Error in Initstring 1" },
				{ "FFF10006" , "Error in Initstring 2" },
				{ "FFF10007" , "Error in Initstring 3" },
				{ "FFF10008" , "Error in Initstring 4" },
				{ "FFF10009" , "Error in dialtype sequence" },
				{ "FFF1000A" , "Error in dialtone sequence" },
				{ "FFF1000B" , "Error in autoanswer sequence" },
				{ "FFF1000C" , "Modem has been removed" },
				{ "FFF1000D" , "Connection could not be established" },
				{ "FFF1000E" , "Login denied. Unknown user." },
				{ "FFF1000F" , "Login denied. Wrong password." },
				{ "FFF10010" , "Login denied. Callback number defined in adapter." },
				{ "FFF10011" , "Error while dialing" },
				{ "FFF80000" , "Function not allowed" },
				{ "FFF80001" , "Invalid project handle" },
				{ "FFF80002" , "Error opening project" },
				{ "FFF80003" , "Error creating program instance of project" },
				{ "FFF80004" , "Error closing project" },
				{ "FFF80005" , "No resp. no more programs found" },
				{ "FFF80006" , "Program not found" },
				{ "FFF80007" , "At least one of the specified parameters is invalid" },
				{ "FFF80008" , "Runtime has expired (demo version)" },
				{ "FFF8000A" , "No resp. invalid data specified" },
				{ "FFF8000B" , "The program selected has no symbol table" },
				{ "FFF8000C" , "Symbol table already opened" },
				{ "FFF8000D" , "No resp. no more symbol entry found" },
				{ "FFF8000E" , "Error reading symbol entry" },
				{ "FFF8000F" , "Symbol not found" },
				{ "FFF80010" , "Operand not found" },
				{ "FFF80011" , "Invalid symbol" },
				{ "FFF80012" , "Invalid operand" },
				{ "FFF80013" , "Invalid filter string" },
				{ "FFF80014" , "Data block (DB) not present" },
				{ "FFF80015" , "Error reading DB block data" },
				{ "FFF80016" , "Error parsing DB block data" },
				{ "FFF80017" , "An opened DB is already present" },
				{ "FFF80018" , "No opened DB present" },
				{ "FFF80019" , "No resp. no more DB component found" },
				{ "FFF8001A" , "Specified DB component not found" },
				{ "FFF8001B" , "Specified DB component is invalid" },
				{ "FFF8001C" , "Specified DB component not matching" },
				{ "FFF8001E" , "Invalid constant" },
				{ "FFF8001F" , "Invalid constant size or format" },
				{ "FFF80020" , "Object type initialization failed" },
				{ "FFF80021" , "Invalid version of message configuration" },
				{ "FFF80022" , "Error opening message configuration" },
				{ "FFF80023" , "Error closing message configuration" },
				{ "FFF80024" , "No resp. no more message entry found" },
				{ "FFF80025" , "No resp. no more language found" },
				{ "FFF80026" , "Database access error" },
				{ "FFF80027" , "Invalid signal number" },
				{ "FFF80028" , "Invalid add. value specification" },
				{ "FFF80029" , "Add. value number invalid" },
				{ "FFF8002A" , "Element type of add. value invalid" },
				{ "FFF8002B" , "Add. value data length invalid" },
				{ "FFF8002C" , "Format specification missing" },
				{ "FFF8002D" , "Format specification invalid" },
				{ "FFF8002E" , "No resp. no more text library found" },
				{ "FFF8002F" , "No resp. no more text library entry found" },
				{ "FFF80030" , "Not enough memory" },
				{ "FFF80031" , "Block type invalid" },
				{ "FFF80032" , "Listing handle invalid" },
				{ "FFF80033" , "Block not present" },
				{ "FFF80034" , "Error reading block data" },
				{ "FFF80035" , "Error parsing block data" },
				{ "FFF80036" , "No resp. no more declaration found" },
				{ "FFF80037" , "No resp. no more attributes found" },
				{ "FFF80038" , "Writing CPU list failed" },
				{ "FFF90000" , "Read error" },
				{ "FFF90001" , "Write error" },
				{ "FFF90002" , "Read error (variable content, type)" },
				{ "FFF90003" , "Wrong PLC type" },
				{ "FFF90064" , "Internal assert wrong" },
				{ "FFFA0000" , "Not applicable" },
				{ "FFFA0001" , "Access invalid element" },
				{ "FFFA0002" , "Access buffer too small" },
				{ "FFFA0003" , "Access buffer invalid S5TIME value" },
				{ "FFFA0004" , "Access buffer invalid S5TIME base" },
				{ "FFFA0005" , "Access buffer invalid S7 COUNTER value" },
				{ "FFFA0006" , "Path missing expanded index" },
				{ "FFFA0007" , "Path invalid" },
				{ "FFFA0008" , "Path end reached" },
				{ "FFFA0009" , "Path unknown field" },
				{ "FFFA000A" , "Unknown child" },
				{ "FFFA000B" , "Array is no value type" },
				{ "FFFA000C" , "Array index missing" },
				{ "FFFA000D" , "Array index invalid" },
				{ "FFFA000E" , "Array index not allowed" },
				{ "FFFA000F" , "Array range not allowed" },
				{ "FFFA0010" , "Array range invalid" },
				{ "FFFA0011" , "UDT has no base type" },
				{ "FFFA0012" , "Unknown error code" },
				{ "FFFA0013" , "Wrong symbol ID" },
				{ "FFFA0014" , "Item access denied" },
				{ "FFFA0015" , "Read only item" },
				{ "FFFA0016" , "Partial errors" },
				{ "FFFA0017" , "Not an instance" },
				{ "FFFA0018" , "Wrong symbol ID path" },
				{ "FFFA0019" , "Symbolic wrong area" },
				{ "FFFA001A" , "Wrong value range" },
				{ "FFFA001B" , "PLC cant deliver" },
				{ "FFFA001C" , "PLC object does not exists" },
				{ "FFFA001D" , "PLC type info missing" },
				{ "FFFA0050" , "Invalid datablock" },
				{ "FFFA0051" , "Datablock is optimized" },
				{ "FFFA0052" , "Invalid Tag" },
				{ "FFFA0053" , "Start address too big" },
				{ "FFFA0054" , "Not allowed symbolic access" },
				{ "FFFA0063" , "Internal error" },
				{ "FFFA0064" , "Internal error 0" },
				{ "FFFA0065" , "Internal error 1" },
				{ "FFFA0066" , "Internal error 2" },
				{ "FFFA0067" , "Internal error 3" },
				{ "FFFA0068" , "Internal error 4" },
				{ "FFFA0069" , "Internal error 5" },
				{ "FFFA006A" , "Internal error 6" },
				{ "FFFA006B" , "Internal error 7" },
				{ "FFFA006C" , "Internal error 8" },
				{ "FFFA006D" , "Internal error 9" },
				{ "FFFA006E" , "File read error" },
				{ "FFFA006F" , "Internal error 11" },
				{ "FFFA0070" , "Internal error 12" },
				{ "FFFA0071" , "Internal error 13" },
				{ "FFFA0072" , "Internal error 14" },
				{ "FFFA0073" , "Internal error 15" },
				{ "FFFA0074" , "Project file not found" },
				{ "FFFA0075" , "Project file unsupported extension" },
				{ "FFFA0076" , "Project folder missing" },
				{ "FFFA0077" , "Internal error 19" },
				{ "FFFA0078" , "Internal error 20" },
				{ "FFFA0079" , "Internal error 21" },
				{ "FFFA007A" , "Internal error 22" },
				{ "FFFA007B" , "Internal error 23" },
				{ "FFFA007C" , "Internal error 24" },
				{ "FFFA007D" , "Internal error 25" },
				{ "FFFA007E" , "Internal error 26" },
				{ "FFFA007F" , "Internal error 27" },
				{ "FFFA0080" , "Internal error 28" },
				{ "FFFA0081" , "Internal error 29" },
				{ "FFFA0082" , "Internal error 30" },
				{ "FFFA0083" , "Internal error 31" },
				{ "FFFA0084" , "Internal error 32" },
				{ "FFFA0085" , "Internal error 33" },
				{ "FFFA0086" , "Internal error 34" },
				{ "FFFA0087" , "Internal error 35" },
				{ "FFFA0088" , "Internal error 36" },
				{ "FFFA0089" , "Internal error 37" },
				{ "FFFA008A" , "Internal error 38" },
				{ "FFFA008B" , "Internal error 39" },
				{ "FFFA008C" , "Internal error 40" },
				{ "FFFA008D" , "Internal error 41" },
				{ "FFFA008E" , "Internal error 42" },
				{ "FFFA008F" , "Internal error 43" },
				{ "FFFA0090" , "Internal error 44" },
				{ "FFFA0091" , "Internal error 45" },
				{ "FFFA0092" , "Internal error 46" },
				{ "FFFA0093" , "Internal error 47" },
				{ "FFFA0094" , "Internal error 48" },
				{ "FFFA0095" , "Internal error 49" },
				{ "FFFA0096" , "Internal error 50" },
				{ "FFFA0097" , "Internal error 51" },
				{ "FFFA0098" , "Internal error 52" },
				{ "FFFA0099" , "Internal error 53" },
				{ "FFFA009A" , "Internal error 54" },
				{ "FFFA009B" , "Internal error 55" },
				{ "FFFA009C" , "Internal error 56" },
				{ "FFFA009D" , "Internal error 57" },
				{ "FFFA009E" , "Internal error 58" },
				{ "FFFA009F" , "Internal error 59" },
				{ "FFFA00A0" , "Internal error 60" },
				{ "FFFA00A1" , "Internal error 61" },
				{ "FFFA00A2" , "Internal error 62" },
				{ "FFFA00A3" , "Internal error 63" },
				{ "FFFA00A4" , "Internal error 64" },
				{ "FFFA00A5" , "Internal error 65" },
				{ "FFFA00A6" , "Internal error 66" },
				{ "FFFA00A7" , "Internal error 67" },
				{ "FFFA00A8" , "Internal error 68" },
				{ "FFFA00A9" , "Internal error 69" },
				{ "FFFA00AA" , "Internal error 70" },
				{ "FFFA00AB" , "Internal error 71" },
				{ "FFFA00AC" , "Internal error 72" },
				{ "FFFA00AD" , "Internal error 73" },
				{ "FFFA00AE" , "Internal error 74" },
				{ "FFFA00AF" , "Internal error 75" },
				{ "FFFA00B0" , "Internal error 76" },
				{ "FFFA00B1" , "Internal error 77" },
				{ "FFFA00B2" , "Internal error 78" },
				{ "FFFA00B3" , "Internal error 79" },
				{ "FFFA00B4" , "Internal error 80" },
				{ "FFFA00B5" , "Internal error 81" },
				{ "FFFA00B6" , "Internal error 82" },
				{ "FFFA00B7" , "Internal error 83" },
				{ "FFFA00B8" , "Internal error 84" },
				{ "FFFA00B9" , "Internal error 85" },
				{ "FFFA00BA" , "Internal error 86" },
				{ "FFFA00BB" , "Internal error 87" },
				{ "FFFA00BC" , "Internal error 88" },
				{ "FFFA00BD" , "Internal error 89" },
				{ "FFFA00BE" , "Internal error 90" },
				{ "FFFA00BF" , "Internal error 91" },
				{ "FFFA00C0" , "Internal error 92" },
				{ "FFFA00C1" , "Internal error 93" },
				{ "FFFA00C2" , "Internal error 94" },
				{ "FFFA00C3" , "Internal error 95" },
				{ "FFFA00C4" , "Internal error 96" },
				{ "FFFA00C5" , "Internal error 97" },
				{ "FFFA00C6" , "Internal error 98" },
				{ "FFFA00C7" , "Internal error 99" },
				{ "FFFA00C8" , "Internal error 100" },
				{ "FFFA00C9" , "Internal error 101" },
				{ "FFFA00CA" , "Internal error 102" },
				{ "FFFA00CB" , "Internal error 103" },
				{ "FFFA00CC" , "Internal error 104" },
				{ "FFFA00CD" , "Internal error 105" },
				{ "FFFA00CE" , "Internal error 106" },
				{ "FFFA00CF" , "Internal error 107" },
				{ "FFFA00D0" , "Internal error 108" },
				{ "FFFA00D1" , "Internal error 109" },
				{ "FFFA00D2" , "Internal error 110" },
				{ "FFFA00D3" , "Internal error 111" },
				{ "FFFA00D4" , "Internal error 112" },
				{ "FFFA00D5" , "Internal error 113" },
				{ "FFFA00D6" , "Internal error 114" },
				{ "FFFA00D7" , "Internal error 115" },
				{ "FFFA00D8" , "Internal error 116" },
				{ "FFFA00D9" , "Internal error 117" },
				{ "FFFA00DA" , "Internal error 118" },
				{ "FFFA00DB" , "Internal error 119" },
				{ "FFFA00DC" , "Internal error 120" },
				{ "FFFA00DD" , "Internal error 121" },
				{ "FFFA00DE" , "Internal error 122" },
				{ "FFFA00DF" , "Internal error 123" },
				{ "FFFA00E0" , "Internal error 124" },
				{ "FFFA00E1" , "Internal error 125" },
				{ "FFFA00E2" , "Internal error 126" },
				{ "FFFA00E3" , "Internal error 127" },
				{ "FFFA00E4" , "Internal error 128" },
				{ "FFFA00E5" , "Internal error 129" },
				{ "FFFA00E6" , "Internal error 130" },
				{ "FFFA00E7" , "Internal error 131" },
				{ "FFFA00E8" , "Internal error 132" },
				{ "FFFA00E9" , "Internal error 133" },
				{ "FFFA00EA" , "Internal error 134" },
				{ "FFFA00EB" , "Internal error 135" },
				{ "FFFA00EC" , "Internal error 136" },
				{ "FFFA00ED" , "Internal error 137" },
				{ "FFFA00EE" , "Internal error 138" },
				{ "FFFA00EF" , "Internal error 139" },
				{ "FFFA00F0" , "Internal error 140" },
				{ "FFFA00F1" , "Internal error 141" },
				{ "FFFA00F2" , "Internal error 142" },
				{ "FFFA00F3" , "Internal error 143" },
				{ "FFFA00F4" , "Internal error 144" },
				{ "FFFA00F5" , "Internal error 145" },
				{ "FFFA00F6" , "Internal error 146" },
				{ "FFFA00F7" , "Internal error 147" },
				{ "FFFA00F8" , "Internal error 148" },
				{ "FFFA00F9" , "Internal error 149" },
				{ "FFFA00FA" , "Internal error 150" },
				{ "FFFA00FB" , "Internal error 151" },
				{ "FFFA00FC" , "Internal error 152" },
				{ "FFFA0190" , "Internal communication error" },
				{ "FFFA0191" , "Internal communication error 0" },
				{ "FFFA0193" , "Internal communication error 2" },
				{ "FFFA0194" , "Write bool range needs modulo 8 start and count" },
				{ "FFFA0195" , "Wrong read type" },
				{ "FFFA0196" , "PLC auto detect failed" },
			};
		}

		public static string GetErrorMessageForCode(int code)
		{
			var error = code.ToString("X");
			return ErrorCodeMapping.TryGetValue(error, out var message) ? message : $"UNKNOWN:{error}";
		}
	}
}